---
# RUN
RUN_NAME: 'UNet_BCL'

# Main configuration file
# IMAGE PARAMETERS
INPUT_IMAGE_SIZE: 512
NUM_CHANNELS: 1

# MODEL PARAMETERS
MODEL: 'UNet'
NUM_CLASSES: 1
MODEL_DEPTH: 4
INIT_LR: 0.0001
NUM_EPOCHS: 150
BATCH_SIZE: 16
THRESHOLD: 0.5
NUM_WORKERS: 1

# DATASET PARAMS
TEST_SPLIT:  0.1
SEED: 42

# PATHS
DATASET_PATH: 'D:/DataStorage/SemSeg/train'
OUTPUT_PATH: 'saved'

# DDP paramenets
GPU_COUNT: 1
MASTER_ADDR: 'localhost'
MASTER_PORT: '12355'