---
# RUN PARAMETERS
MODEL: 'UNet'
DSET: 'scarp'

# PATHS
DATASET_PATH: 'D:/DataStorage/SemSeg/train'
OUTPUT_PATH: 'saved'

# IMAGE PARAMETERS
INPUT_IMAGE_SIZE: 512
NUM_CHANNELS: 1

# MODEL PARAMETERS
LOSS: 'BinDICE' # BinDICE | BinC1 | SdmDICE | WeightedBCL | SdmC1 | SdmC2 | SdmC3
NUM_CLASSES: 1
INIT_LR: 0.0001
L2_DECAY: 0.00001
DROPOUT: 0.1
NUM_EPOCHS: 150
BATCH_SIZE: 16
THRESHOLD: 0.5
NUM_WORKERS: 1

# DATASET PARAMS
TEST_SPLIT:  0.1
SEED: 42

# DDP paramenets
NUM_GPU: 1
MASTER_ADDR: 'localhost'
MASTER_PORT: '12355'